### ISSUE TITLE
Error when Using Tensorflow-1.13.1-gpu lib. 

### ISSUE THREAD

**Issue by GaryFigno** [Neargye/hello_tf_c_api#36]
Thanks for your work on TF c api.
When I was trying to compile your work on Ubuntu18.04 and g++ with the Tensorflow 1.13.1-gpu library, error occurred.
The error information is as follow:
tf_utils.hpp:94:24: error: there are no arguments to ‘TF_TensorElementCount’ that depend on a template parameter, so a declaration of ‘TF_TensorElementCount’ must be available.
So I guess the tf_utils is using some functions has not been defined in Tensorflow gpu library?

**Comment by Neargye** [comment]
Fix in master. Test on 1.3.1 work ok.

**Comment by GaryFigno** [comment]
Thank you very much. Successfully compiled and ran.
